a=int(input('Enter the value of a : '))
b=int(input('Enter the value of b:'))
print('The value of A before swapping ' ,a )
print('The value of B before swapping' , b)
a,b=b,a # simple way to swap two values :)
print('The value of A After swapping ' ,a )
print('The value of B After swapping' , b)
